import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster 
          toastOptions={{
            unstyled: true,
            classNames: {
              error: 'text-red-400 border-l-4 border-l-red-400 bg-white flex items-center justify-start rounded-md py-3 px-7 gap-1',
              success: 'text-green-400 border-l-4 border-l-green-400 bg-white flex items-center justify-start rounded-md py-3 px-7 gap-1',
              warning: 'text-yellow-400 border-l-4 border-l-yellow-400 bg-white flex items-center justify-start rounded-md py-3 px-7 gap-1',
              info: 'text-blue-400 border-l-4 border-l-blue-400 bg-white flex items-center justify-start rounded-md py-3 px-7 gap-1',
            },
          }}
        />
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
